export const CONTRACT_ABI = [
  "event AgentRated(uint256 indexed bountyId, address indexed agent, address indexed requester, uint8 score)",
  "event BountyAccepted(uint256 indexed id, address indexed agent, uint256 workDeadline)",
  "event BountyCancelled(uint256 indexed id, address indexed requester, uint256 amount, bool mutual)",
  "event BountyCreated(uint256 indexed id, address indexed requester, address indexed agent, uint256 amount, string description, uint256 workDuration, uint256 reviewPeriod)",
  "event BountyRefunded(uint256 indexed id, address indexed requester, uint256 amount)",
  "event BountyReleased(uint256 indexed id, address indexed agent, uint256 amount)",
  "event CancellationApprovalUpdated(uint256 indexed id, address indexed party, bool approved)",
  "event WorkSubmitted(uint256 indexed id, address indexed agent, string submission, uint256 reviewDeadline)",
  "function acceptBounty(uint256 id)",
  "function agentRatings(address, uint256) view returns (address requester, uint256 bountyId, uint8 score, uint256 ratedAt)",
  "function bounties(uint256 id) view returns ((address requester, address agent, uint256 amount, string description, string submission, uint8 status, uint256 createdAt, uint256 workDeadline, uint256 reviewDeadline, uint256 workDuration, uint256 reviewPeriod, bool requesterCancellationApproved, bool agentCancellationApproved))",
  "function bountyCount() view returns (uint256)",
  "function bountyRated(uint256) view returns (bool)",
  "function cancelOpenBounty(uint256 id)",
  "function createBounty(address designatedAgent, string description, uint256 workDuration, uint256 reviewPeriod) payable returns (uint256 id)",
  "function finalize(uint256 id)",
  "function getAgentRatingSummary(address agent) view returns (uint256 totalScore, uint256 count)",
  "function rateAgent(uint256 id, uint8 score)",
  "function refundExpiredBounty(uint256 id)",
  "function release(uint256 id)",
  "function setCancellationApproval(uint256 id, bool approved)",
  "function submitWork(uint256 id, string submission)",
] as const;
